# Generated by Django 5.2.5 on 2025-08-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='allocated_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
